import { StyleSheet } from 'react-native';
import { borderRadius, colors, fontSize, fontWeight, spacing } from '../../../../lib/design-tokens';

export const styles = StyleSheet.create({
  // ===== STYLES COMMUNS =====
  container: {
    flex: 1,
    backgroundColor: colors.gray50,
  },
  header: {
    backgroundColor: colors.sessionsPrimary,
    borderRadius: borderRadius.lg,
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
    paddingVertical: spacing.xl,
    paddingHorizontal: spacing.xl,
    position: 'relative',
    overflow: 'hidden',
  },
  tabsContainer: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  tab: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    marginRight: spacing.sm,
    borderRadius: 20,
    backgroundColor: colors.gray100,
  },
  activeTab: {
    backgroundColor: colors.sessionsPrimary,
  },
  tabText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: colors.gray500,
  },
  activeTabText: {
    color: colors.white,
  },
  sessionTitle: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    marginBottom: spacing.xs,
    color: '#333',
  },
  mentorInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mentorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: spacing.md,
  },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  avatarInitial: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: '#666',
  },
  mentorName: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: '#333',
  },
  mentorTitle: {
    fontSize: fontSize.sm,
    color: '#666',
  },
  description: {
    fontSize: fontSize.sm,
    color: '#333',
    lineHeight: 20,
  },
  bookButton: {
    backgroundColor: colors.sessionsPrimary,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    shadowColor: colors.sessionsPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
  },
  disabledButton: {
    backgroundColor: '#cccccc',
  },
  bookButtonText: {
    color: colors.white,
    fontWeight: fontWeight.semibold,
    fontSize: fontSize.base,
  },

  // ===== STYLES SPÉCIFIQUES À LA LISTE =====
  backgroundCircle1: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 80,
    height: 80,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  backgroundCircle2: {
    position: 'absolute',
    bottom: -30,
    left: -30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  titleSection: {
    flex: 0.6,
    marginRight: spacing.lg,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
    flexWrap: 'nowrap',
  },
  title: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    color: colors.white,
    marginLeft: 6,
    flexShrink: 0,
  },
  subtitle: {
    fontSize: fontSize.xs,
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 16,
  },
  statsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 0.4,
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  statItem: {
    alignItems: 'center',
    width: 42,
    marginBottom: spacing.xs,
  },
  statNumber: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.white,
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 8,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    lineHeight: 10,
    flexWrap: 'wrap',
  },
  searchContainer: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  searchIcon: {
    marginRight: spacing.sm,
  },
  searchInput: {
    flex: 1,
    fontSize: fontSize.sm,
    color: colors.gray800,
    padding: 0,
  },
  sessionsList: {
    paddingHorizontal: spacing.lg,
    paddingBottom: 100,
  },
  sessionCard: {
    borderRadius: borderRadius.lg,
    backgroundColor: colors.white,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    padding: spacing.lg,
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
    alignItems: 'center',
  },
  sessionInfo: {
    flex: 1,
  },
  sessionDuration: {
    fontSize: fontSize.base,
    color: '#333',
    marginBottom: 6,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  price: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.sessionsPrimary,
  },
  mentorSection: {
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    paddingTop: 12,
    marginBottom: spacing.md,
  },
  descriptionContainer: {
    marginBottom: spacing.lg,
  },
  bookedSessionCard: {
    borderRadius: borderRadius.lg,
    backgroundColor: colors.white,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    padding: spacing.lg,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmedBadge: {
    backgroundColor: colors.success,
  },
  pendingBadge: {
    backgroundColor: colors.warning,
  },
  completedBadge: {
    backgroundColor: '#6366f1',
  },
  statusText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    color: colors.white,
  },
  sessionDetails: {
    marginTop: spacing.md,
    marginBottom: spacing.lg,
  },
  sessionDetailItem: {
    marginBottom: spacing.sm,
  },
  sessionDetailLabel: {
    fontSize: 13,
    color: '#666',
    marginBottom: 2,
  },
  sessionDetailValue: {
    fontSize: 15,
    color: '#333',
    fontWeight: fontWeight.medium,
  },
  bookedSessionActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  joinMeetingButton: {
    flex: 1,
    backgroundColor: colors.sessionsPrimary,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    marginRight: spacing.sm,
    shadowColor: colors.sessionsPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
  },
  joinMeetingText: {
    color: colors.white,
    fontWeight: fontWeight.semibold,
    fontSize: 15,
  },
  messageMentorButton: {
    flex: 1,
    backgroundColor: colors.white,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  messageMentorText: {
    color: '#333',
    fontWeight: fontWeight.semibold,
    fontSize: 15,
  },
  calendarContainer: {
    padding: spacing.lg,
  },
  calendarContentContainer: {
    paddingBottom: 120,
  },
  calendarHeader: {
    marginBottom: spacing.lg,
  },
  calendarTitle: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    marginBottom: spacing.xs,
    color: '#333',
  },
  calendarSubtitle: {
    fontSize: fontSize.base,
    color: '#666',
  },
  calendarView: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  calendarMonthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.sm,
  },
  monthNavButton: {
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: colors.gray100,
  },
  calendarMonthText: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: '#333',
  },
  weekdayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.md,
  },
  weekdayText: {
    fontSize: fontSize.sm,
    color: '#666',
    textAlign: 'center',
    width: 40,
    fontWeight: fontWeight.semibold,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  calendarDay: {
    width: 40,
    height: 40,
    margin: 2,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  dayButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  currentDayButton: {
    backgroundColor: colors.sessionsPrimary,
  },
  sessionDayButton: {
    backgroundColor: colors.gray100,
  },
  calendarDayText: {
    fontSize: fontSize.sm,
    color: '#333',
  },
  currentDayText: {
    color: colors.white,
    fontWeight: fontWeight.bold,
  },
  sessionDayText: {
    color: colors.sessionsPrimary,
    fontWeight: fontWeight.semibold,
  },
  sessionIndicator: {
    position: 'absolute',
    bottom: 0,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.sessionsPrimary,
  },
  upcomingSessionsSection: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  upcomingSessionsTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    marginBottom: spacing.md,
    color: '#333',
  },
  upcomingSessionItem: {
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  upcomingSessionTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    marginBottom: spacing.xs,
    color: '#333',
  },
  upcomingSessionDate: {
    fontSize: fontSize.sm,
    color: '#666',
    marginBottom: spacing.xs,
  },
  mentorText: {
    fontSize: fontSize.xs,
    color: '#999',
  },
  statsSection: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  statsSectionTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    marginBottom: spacing.md,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  lastStatRow: {
    borderBottomWidth: 0,
  },
  statRowLabel: {
    fontSize: fontSize.sm,
    color: '#666',
  },
  statRowValue: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  starIcon: {
    fontSize: fontSize.sm,
    color: colors.warning,
    marginLeft: spacing.xs,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  modalHeader: {
    padding: spacing.xl,
    paddingTop: 60,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray200,
    backgroundColor: colors.white,
  },
  closeButton: {
    position: 'absolute',
    top: 50,
    right: 15,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.gray100,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 1000,
  },
  modalTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.bold,
    color: colors.gray800,
    marginBottom: spacing.sm,
  },
  modalSubtitle: {
    fontSize: fontSize.base,
    color: colors.gray500,
  },
  modalContent: {
    flex: 1,
    padding: spacing.xl,
  },
  sectionContainer: {
    marginBottom: spacing.xxl,
  },
  sectionTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    color: colors.gray800,
    marginBottom: spacing.md,
  },
  modalCalendarView: {
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
  },
  modalCalendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  modalCalendarMonthText: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.gray800,
  },
  modalWeekdayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.md,
  },
  modalWeekdayText: {
    fontSize: fontSize.sm,
    color: colors.gray500,
    textAlign: 'center',
    width: 40,
    fontWeight: fontWeight.semibold,
  },
  modalCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  modalCalendarDay: {
    width: 40,
    height: 40,
    margin: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDayButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  selectedDayButton: {
    backgroundColor: colors.sessionsPrimary,
  },
  modalCalendarDayText: {
    fontSize: fontSize.sm,
    color: colors.gray800,
  },
  selectedDayText: {
    color: colors.white,
    fontWeight: fontWeight.bold,
  },
  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  timeButton: {
    width: '48%',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.white,
    alignItems: 'center',
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  selectedTimeButton: {
    backgroundColor: colors.sessionsPrimary,
    borderColor: colors.sessionsPrimary,
  },
  timeButtonText: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: '#333',
  },
  selectedTimeButtonText: {
    color: colors.white,
    fontWeight: fontWeight.bold,
  },
  notesInput: {
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    fontSize: fontSize.sm,
    color: colors.gray800,
    minHeight: 100,
    backgroundColor: colors.white,
  },
  summaryContainer: {
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xxl,
  },
  summaryTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.gray800,
    marginBottom: spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  summaryLabel: {
    fontSize: fontSize.sm,
    color: colors.gray500,
  },
  summaryValue: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    color: colors.gray800,
  },
  confirmButton: {
    backgroundColor: colors.sessionsPrimary,
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  confirmButtonText: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.white,
  },

  // ===== STYLES SPÉCIFIQUES AU DÉTAIL =====
  detailContainer: {
    flex: 1,
    padding: spacing.lg,
    backgroundColor: '#f7f8fc',
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  detailSessionTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.bold,
    marginLeft: spacing.lg,
    flex: 1,
    color: '#333',
  },
  notFound: {
    fontSize: fontSize.lg,
    textAlign: 'center',
    marginTop: spacing.xl,
    color: '#333',
  },
  sessionMetadata: {
    flexDirection: 'row',
    marginBottom: spacing.xxl,
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  metadataItem: {
    flex: 1,
  },
  metadataLabel: {
    fontSize: 15,
    color: '#666',
    marginBottom: spacing.xs,
  },
  metadataValue: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: '#333',
  },
  detailSectionContainer: {
    marginBottom: spacing.xxl,
  },
  detailSectionTitle: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    marginBottom: 14,
    color: '#333',
  },
  detailDescription: {
    fontSize: fontSize.base,
    lineHeight: 24,
    color: '#333',
  },
  mentorCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  mentorHeader: {
    flexDirection: 'row',
    marginBottom: spacing.md,
  },
  detailMentorAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginRight: spacing.lg,
  },
  detailAvatarPlaceholder: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.lg,
  },
  detailAvatarInitial: {
    fontSize: 26,
    fontWeight: fontWeight.bold,
    color: '#666',
  },
  detailMentorInfo: {
    justifyContent: 'center',
  },
  detailMentorName: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    marginBottom: spacing.xs,
    color: '#333',
  },
  detailMentorTitle: {
    fontSize: 15,
    color: '#666',
  },
  mentorBio: {
    fontSize: 15,
    lineHeight: 22,
    color: '#333',
  },
  dateTimeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  dateTimeOption: {
    width: '48%',
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 14,
    marginBottom: 14,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  selectedDateTime: {
    backgroundColor: colors.sessionsPrimary,
    borderColor: colors.sessionsPrimary,
  },
  unavailableDateTime: {
    backgroundColor: '#f5f5f5',
    opacity: 0.8,
    borderColor: '#e0e0e0',
  },
  dateText: {
    fontSize: 15,
    fontWeight: fontWeight.medium,
    marginBottom: 6,
    color: '#333',
  },
  timeText: {
    fontSize: 17,
    fontWeight: fontWeight.bold,
    color: '#333',
  },
  selectedDateTimeText: {
    color: colors.white,
  },
  unavailableDateTimeText: {
    color: '#999',
  },
  unavailableText: {
    fontSize: fontSize.xs,
    color: '#ff3b30',
    marginTop: 6,
    fontWeight: fontWeight.medium,
  },
  bookingContainer: {
    marginTop: spacing.lg,
    marginBottom: spacing.xxxl,
  },
});
