workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/Chabaqa.xcworkspace"
        XCODE_SCHEME: "Chabaqa"
        BUNDLE_ID: "com.mariembenali.chabaqa"
      node: 20
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          npx expo prebuild --platform ios --clean
          cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - louay_rjili@ieee.org
        notify:
          success: true
          failure: true

  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.mariembenali.chabaqa"
      node: 20
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Run Expo prebuild
        script: |
          npx expo prebuild --platform android --clean
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - louay_rjili@ieee.org
        notify:
          success: true
          failure: true
