# SIMPLE VERSION - No groups needed, all vars inline
# Use this if you want to test quickly without creating groups in Codemagic dashboard
# To use: Rename this to codemagic.yaml (backup the original first)

workflows:
  android-production:
    name: Chabaqa Android APK (Simple)
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      vars:
        # App configuration
        PACKAGE_NAME: "com.mariembenali.chabaqa"
        EXPO_PUBLIC_API_URL: "http://51.254.132.77:3000"
        
        # Google OAuth credentials (inline, no group needed)
        EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID: "759626859985-m0uo1oppudgks98ivsjk57ujpu5fbhfp.apps.googleusercontent.com"
        EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID: "759626859985-m0uo1oppudgks98ivsjk57ujpu5fbhfp.apps.googleusercontent.com"
        EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID: "759626859985-m0uo1oppudgks98ivsjk57ujpu5fbhfp.apps.googleusercontent.com"
        EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID: "759626859985-m0uo1oppudgks98ivsjk57ujpu5fbhfp.apps.googleusercontent.com"
      node: 20
      java: 17
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing npm dependencies..."
          npm ci
      
      - name: Create .env file
        script: |
          echo "Creating .env file with environment variables..."
          cat > .env << EOF
          EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL
          EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID
          EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID
          EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID
          EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=$EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
          EOF
          echo ".env file created successfully"
          cat .env
      
      - name: Run Expo prebuild for Android
        script: |
          echo "Running Expo prebuild to generate native Android project..."
          npx expo prebuild --platform android --clean
          echo "Prebuild completed successfully"
      
      - name: Set up Android SDK
        script: |
          echo "Configuring Android SDK..."
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          cat "$CM_BUILD_DIR/android/local.properties"
      
      - name: Build unsigned APK
        script: |
          echo "Building Android APK..."
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon --stacktrace
          echo "APK built successfully!"
      
      - name: Verify APK
        script: |
          echo "Verifying APK file..."
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          if [ -f "$APK_PATH" ]; then
            echo "✅ APK found at: $APK_PATH"
            ls -lh "$APK_PATH"
          else
            echo "❌ APK not found!"
            exit 1
          fi
    
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/mapping/release/mapping.txt
    
    publishing:
      email:
        recipients:
          - louay_rjili@ieee.org
        notify:
          success: true
          failure: true
