// Ce fichier n'est pas une route, mais un fichier de styles
// Pour Expo Router, on peut ajouter cette ligne pour éviter les avertissements
export const unstable_settings = {
  isNotARoute: true,
};

import { StyleSheet, Platform } from 'react-native';
import { borderRadius, fontSize, fontWeight, spacing } from '../../lib/design-tokens';

// Dark theme colors matching PaymentScreen
const darkColors = {
  background: '#111827',
  card: '#1f2937',
  cardBorder: '#374151',
  inputBg: '#374151',
  text: '#ffffff',
  textSecondary: '#9ca3af',
  textMuted: '#6b7280',
  primary: '#8e78fb',
  primaryLight: 'rgba(142, 120, 251, 0.15)',
  success: '#22d3ee',
  error: '#ef4444',
  errorBg: 'rgba(239, 68, 68, 0.1)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: darkColors.background,
  },
  background: {
    flex: 1,
    backgroundColor: darkColors.background,
  },
  safeAreaTop: {
    height: Platform.OS === 'ios' ? 50 : 30,
    width: '100%',
  },
  scrollContent: {
    flexGrow: 1,
    padding: spacing.xl,
    paddingBottom: 40,
  },
  headerContainer: {
    alignItems: 'flex-start',
    marginBottom: spacing.lg,
    width: '100%',
    paddingTop: spacing.sm,
  },
  iconContainer: {
    marginBottom: spacing.lg,
  },
  iconBackground: {
    width: 64,
    height: 64,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: darkColors.card,
  },
  headerTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.bold,
    color: darkColors.text,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: fontSize.base,
    color: darkColors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  card: {
    backgroundColor: darkColors.card,
    borderRadius: 20,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
    marginBottom: spacing.xl,
  },
  form: {
    gap: spacing.xl,
  },
  stepIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  stepIndicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepDot: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: darkColors.inputBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: darkColors.cardBorder,
  },
  stepDotActive: {
    backgroundColor: darkColors.primary,
    borderColor: darkColors.primary,
  },
  stepDotText: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    color: darkColors.textMuted,
  },
  stepDotTextActive: {
    color: darkColors.text,
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: darkColors.cardBorder,
    marginHorizontal: spacing.sm,
  },
  stepLineActive: {
    backgroundColor: darkColors.primary,
  },
  stepContent: {
    gap: spacing.lg,
  },
  stepTitle: {
    fontSize: 22,
    fontWeight: fontWeight.bold,
    color: darkColors.text,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  stepSubtitle: {
    fontSize: fontSize.sm,
    color: darkColors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  inputContainer: {
    gap: spacing.sm,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: darkColors.textSecondary,
    marginBottom: 4,
  },
  input: {
    backgroundColor: darkColors.inputBg,
    borderRadius: 12,
    padding: spacing.lg,
    fontSize: fontSize.base,
    color: darkColors.text,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  radioGroup: {
    gap: spacing.md,
  },
  radioOption: {
    backgroundColor: darkColors.inputBg,
    borderRadius: 12,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  radioOptionSelected: {
    borderColor: darkColors.primary,
    backgroundColor: darkColors.primaryLight,
  },
  radioText: {
    fontSize: fontSize.base,
    color: darkColors.textSecondary,
    fontWeight: fontWeight.medium,
  },
  radioTextSelected: {
    color: darkColors.primary,
    fontWeight: fontWeight.semibold,
  },
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.lg,
    marginTop: spacing.lg,
  },
  primaryButton: {
    borderRadius: 30,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    minWidth: 150,
  },
  primaryButtonText: {
    color: darkColors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButton: {
    backgroundColor: darkColors.inputBg,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
    borderRadius: 30,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    minWidth: 100,
  },
  secondaryButtonText: {
    color: darkColors.textSecondary,
    fontSize: 16,
    fontWeight: '500',
  },
  disabledButton: {
    opacity: 0.5,
  },
  successMessage: {
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.2)',
    borderRadius: 12,
    padding: spacing.lg,
  },
  successText: {
    color: darkColors.success,
    fontSize: 14,
    textAlign: 'center',
  },
  errorMessage: {
    backgroundColor: darkColors.errorBg,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: 12,
    padding: spacing.lg,
  },
  errorText: {
    color: darkColors.error,
    fontSize: 14,
  },
  footer: {
    alignItems: 'center',
    marginTop: spacing.xl,
  },
  footerText: {
    color: darkColors.textMuted,
    fontSize: 12,
  },
  // Option cards for Step 2
  optionSection: {
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkColors.inputBg,
    borderRadius: 16,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  optionCardSelected: {
    borderColor: darkColors.primary,
    backgroundColor: darkColors.primaryLight,
  },
  optionIconContainer: {
    marginRight: spacing.lg,
  },
  optionIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionContent: {
    flex: 1,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: darkColors.text,
    marginBottom: 4,
  },
  optionDescription: {
    fontSize: 13,
    color: darkColors.textSecondary,
    lineHeight: 18,
  },
  radioButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: darkColors.textMuted,
    backgroundColor: 'transparent',
  },
  radioButtonSelected: {
    borderColor: darkColors.primary,
    backgroundColor: darkColors.primary,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: darkColors.text,
    marginBottom: spacing.md,
    marginTop: spacing.md,
  },
  membershipFeeContainer: {
    flexDirection: 'row',
    marginTop: spacing.md,
    gap: spacing.md,
  },
  currencySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkColors.card,
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    minWidth: 90,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  currencyText: {
    color: darkColors.text,
    fontSize: 14,
    fontWeight: '600',
    marginRight: spacing.sm,
  },
  feeInput: {
    flex: 1,
    backgroundColor: darkColors.card,
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    color: darkColors.text,
    fontSize: 16,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: darkColors.card,
    borderRadius: 20,
    padding: spacing.xl,
    width: '85%',
    maxWidth: 340,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: darkColors.text,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  currencyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    marginBottom: spacing.sm,
    backgroundColor: darkColors.inputBg,
  },
  currencyOptionSelected: {
    backgroundColor: darkColors.primaryLight,
    borderWidth: 1,
    borderColor: darkColors.primary,
  },
  currencyCode: {
    fontSize: 16,
    fontWeight: '600',
    color: darkColors.text,
    marginRight: spacing.sm,
  },
  currencyName: {
    fontSize: 13,
    color: darkColors.textSecondary,
    flex: 1,
  },
  socialLinksContainer: {
    gap: spacing.md,
  },
  socialLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  socialIconContainer: {
    width: 48,
    height: 48,
  },
  socialIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialInput: {
    flex: 1,
    backgroundColor: darkColors.inputBg,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    paddingVertical: 14,
    color: darkColors.text,
    fontSize: 15,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  photoUploadContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  photoUploadButton: {
    marginBottom: spacing.sm,
  },
  photoUploadGradient: {
    width: 80,
    height: 80,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedImage: {
    width: 76,
    height: 76,
    borderRadius: 18,
  },
  photoUploadText: {
    fontSize: 13,
    color: darkColors.textSecondary,
    textAlign: 'center',
  },
  inputError: {
    borderColor: darkColors.error,
    backgroundColor: darkColors.errorBg,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  modalCloseButton: {
    fontSize: 20,
    color: darkColors.textSecondary,
    fontWeight: '600',
  },
  currencySymbol: {
    fontSize: 20,
    fontWeight: '600',
    color: darkColors.text,
    width: 40,
    textAlign: 'center',
  },
  currencyInfo: {
    flex: 1,
    marginLeft: spacing.md,
  },
  checkMark: {
    fontSize: 18,
    color: darkColors.success,
    fontWeight: '600',
  },

  // Success Page Styles - Dark Theme
  successCard: {
    backgroundColor: darkColors.card,
    borderRadius: 24,
    padding: 32,
    margin: spacing.xl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  successDecorations: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 100,
  },
  successDecorationLeft: {
    position: 'absolute',
    top: spacing.xl,
    left: 30,
  },
  successDecorationRight: {
    position: 'absolute',
    top: spacing.xl,
    right: 30,
  },
  successIconContainer: {
    marginBottom: spacing.xl,
    marginTop: spacing.lg,
  },
  successCheckContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCheckGradient: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#22d3ee',
  },
  successCheckIcon: {
    fontSize: 32,
    color: darkColors.background,
    fontWeight: 'bold',
  },
  successPartyIcon: {
    fontSize: 24,
  },
  successStarIcon: {
    fontSize: 20,
  },
  successContent: {
    alignItems: 'center',
    width: '100%',
  },
  successTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: darkColors.text,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  successSubtitle: {
    fontSize: 18,
    fontWeight: '600',
    color: darkColors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  successDescription: {
    fontSize: 14,
    color: darkColors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.xl,
  },
  successFeatures: {
    width: '100%',
    marginBottom: spacing.xl,
  },
  successFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkColors.inputBg,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  successFeatureIcon: {
    fontSize: 18,
    marginRight: spacing.md,
  },
  successFeatureText: {
    fontSize: 14,
    color: darkColors.textSecondary,
    fontWeight: '500',
  },
  successActions: {
    width: '100%',
    gap: spacing.md,
  },
  successPrimaryButton: {
    borderRadius: 30,
    overflow: 'hidden',
  },
  successButtonGradient: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
  },
  successPrimaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: darkColors.text,
    textAlign: 'center',
  },
  successSecondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    backgroundColor: darkColors.inputBg,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  successSecondaryButtonText: {
    fontSize: 14,
    color: darkColors.textSecondary,
    textAlign: 'center',
    fontWeight: '500',
  },
  successParticles: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  successParticle: {
    position: 'absolute',
    top: Math.random() * 200 + 100,
  },
  successParticleText: {
    fontSize: 14,
    opacity: 0.7,
  },
  // Modern Success Styles - Dark Theme
  modernFloatingElement: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    opacity: 0.3,
  },
  modernElement1: {
    top: '15%',
    left: '10%',
  },
  modernElement2: {
    top: '25%',
    right: '15%',
  },
  modernElement3: {
    bottom: '20%',
    left: '20%',
  },
  modernFloatingGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
  },
  modernSuccessCard: {
    backgroundColor: darkColors.card,
    borderRadius: 24,
    padding: 32,
    margin: spacing.xl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  modernSuccessIcon: {
    marginBottom: spacing.xl,
    position: 'relative',
  },
  modernIconGradient: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modernCheckIcon: {
    fontSize: 40,
    color: darkColors.background,
    fontWeight: '900',
  },
  modernIconGlow: {
    position: 'absolute',
    top: -10,
    left: -10,
    right: -10,
    bottom: -10,
    borderRadius: 60,
    backgroundColor: 'rgba(34, 211, 238, 0.2)',
    opacity: 0.8,
  },
  modernContent: {
    alignItems: 'center',
    width: '100%',
  },
  modernTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: darkColors.text,
    textAlign: 'center',
    marginBottom: spacing.sm,
    letterSpacing: 0.5,
  },
  modernSubtitle: {
    fontSize: 18,
    fontWeight: '600',
    color: darkColors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.md,
    lineHeight: 26,
  },
  modernDescription: {
    fontSize: 14,
    color: darkColors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
    opacity: 0.9,
  },
  modernStats: {
    width: '100%',
    marginBottom: 32,
    gap: spacing.md,
  },
  modernStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkColors.inputBg,
    borderRadius: 16,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  modernStatIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  modernStatEmoji: {
    fontSize: 20,
  },
  modernStatText: {
    fontSize: 14,
    color: darkColors.text,
    fontWeight: '500',
    flex: 1,
  },
  modernActions: {
    width: '100%',
    gap: spacing.md,
  },
  modernPrimaryButton: {
    borderRadius: 30,
    overflow: 'hidden',
  },
  modernButtonGradient: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modernPrimaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: darkColors.text,
    marginRight: spacing.sm,
  },
  modernButtonIcon: {
    fontSize: 16,
    color: darkColors.text,
    fontWeight: '600',
  },
  modernSecondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    backgroundColor: darkColors.inputBg,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  modernSecondaryButtonText: {
    fontSize: 14,
    color: darkColors.textSecondary,
    textAlign: 'center',
    fontWeight: '500',
  },
  // Minimalist Success Styles - Dark Theme
  minimalistBackground: {
    flex: 1,
    backgroundColor: darkColors.background,
  },
  confettiParticle: {
    position: 'absolute',
    top: 0,
  },
  confettiShape: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  spiralContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  spiral: {
    position: 'absolute',
    fontSize: 24,
    opacity: 0.6,
  },
  spiral1: {
    top: '20%',
    right: '25%',
    transform: [{ rotate: '45deg' }],
  },
  spiral2: {
    bottom: '30%',
    left: '15%',
    transform: [{ rotate: '-30deg' }],
  },
  spiral3: {
    top: '60%',
    right: '10%',
    transform: [{ rotate: '120deg' }],
  },
  minimalistContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  minimalistContent: {
    alignItems: 'center',
    width: '100%',
  },
  minimalistIconContainer: {
    marginBottom: 32,
    alignItems: 'center',
  },
  minimalistIcon: {
    backgroundColor: '#22d3ee',
    borderRadius: 24,
    padding: spacing.lg,
  },
  iconGrid: {
    width: 100,
    height: 100,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  iconCell: {
    width: 32,
    height: 32,
    backgroundColor: darkColors.inputBg,
    borderRadius: 8,
    margin: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  iconCellCenter: {
    backgroundColor: darkColors.primary,
    borderColor: darkColors.primary,
  },
  iconFace: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  iconEyes: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  iconEye: {
    width: 3,
    height: 3,
    backgroundColor: darkColors.text,
    borderRadius: 1.5,
    marginHorizontal: 2,
  },
  iconMouth: {
    width: 8,
    height: 2,
    backgroundColor: darkColors.text,
    borderRadius: 1,
  },
  minimalistTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: darkColors.text,
    textAlign: 'center',
    marginBottom: spacing.sm,
    letterSpacing: -0.5,
  },
  minimalistSubtitle: {
    fontSize: 16,
    color: darkColors.textSecondary,
    textAlign: 'center',
    marginBottom: 48,
    fontWeight: '400',
  },
  minimalistActions: {
    width: '100%',
    gap: spacing.md,
  },
  minimalistPrimaryButton: {
    backgroundColor: darkColors.text,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 30,
  },
  minimalistPrimaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: darkColors.background,
    textAlign: 'center',
  },
  minimalistSecondaryButton: {
    backgroundColor: 'transparent',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: darkColors.cardBorder,
  },
  minimalistSecondaryButtonText: {
    fontSize: 14,
    color: darkColors.textSecondary,
    textAlign: 'center',
    fontWeight: '500',
  },
});

export default styles;
