// Ce fichier n'est pas une route, mais un fichier de styles
// Pour Expo Router, on peut ajouter cette ligne pour éviter les avertissements
export const unstable_settings = {
  isNotARoute: true,
};

import { StyleSheet } from 'react-native';
import { borderRadius, colors, fontSize, fontWeight, spacing } from '../../lib/design-tokens';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  background: {
    flex: 1,
  },
  safeAreaTop: {
    height: 50,
    width: '100%',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: spacing.xl,
  },
  headerContainer: {
    alignItems: 'flex-start',
    marginBottom: spacing.lg,
    width: '100%',
    paddingTop: spacing.sm,
  },
  iconContainer: {
    marginBottom: spacing.lg,
  },
  iconBackground: {
    width: 64,
    height: 64,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.bold,
    color: colors.gray800,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: fontSize.base,
    color: colors.gray600,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  card: {
    backgroundColor: colors.authCardBackground,
    borderRadius: borderRadius.xxl,
    padding: spacing.xxxl,
    borderWidth: 1,
    borderColor: colors.authCardBorder,
    marginBottom: spacing.xxxl,
  },
  form: {
    gap: spacing.xxl,
  },
  stepIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  stepIndicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepDot: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  stepDotActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  stepDotText: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    color: colors.gray500,
  },
  stepDotTextActive: {
    color: colors.white,
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    marginHorizontal: spacing.sm,
  },
  stepLineActive: {
    backgroundColor: colors.primary,
  },
  stepContent: {
    gap: spacing.xxl,
  },
  stepTitle: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.gray800,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  stepSubtitle: {
    fontSize: fontSize.sm,
    color: colors.gray500,
    textAlign: 'center',
    marginBottom: spacing.xxl,
  },
  inputContainer: {
    gap: spacing.sm,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: colors.gray800,
  },
  input: {
    backgroundColor: colors.authInputBackground,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    fontSize: fontSize.base,
    color: colors.gray800,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  radioGroup: {
    gap: spacing.md,
  },
  radioOption: {
    backgroundColor: colors.authInputBackground,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
  },
  radioOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  radioText: {
    fontSize: fontSize.base,
    color: colors.gray600,
    fontWeight: fontWeight.medium,
  },
  radioTextSelected: {
    color: colors.primary,
    fontWeight: fontWeight.semibold,
  },
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.lg,
    marginTop: spacing.sm,
  },
  primaryButton: {
    borderRadius: spacing.lg,
    padding: spacing.lg,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: spacing.sm,
    elevation: spacing.sm,
    minWidth: 150,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '600',
  },
  secondaryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: spacing.lg,
    padding: spacing.lg,
    alignItems: 'center',
    minWidth: 100,
  },
  secondaryButtonText: {
    color: colors.gray700,
    fontSize: spacing.lg,
    fontWeight: '500',
  },
  disabledButton: {
    opacity: 0.5,
  },
  successMessage: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.2)',
    borderRadius: spacing.lg,
    padding: spacing.lg,
  },
  successText: {
    color: colors.successDark,
    fontSize: 14,
    textAlign: 'center',
  },
  errorMessage: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: spacing.lg,
    padding: spacing.lg,
  },
  errorText: {
    color: colors.errorDark,
    fontSize: 14,
  },
  footer: {
    alignItems: 'center',
  },
  footerText: {
    color: colors.gray500,
    fontSize: spacing.md,
  },
  // Nouveaux styles pour les fonctionnalités ajoutées
  optionSection: {
    gap: spacing.lg,
    marginBottom: spacing.xl,
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: spacing.md,
    padding: spacing.lg,
  },
  optionCardSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(142, 120, 251, 0.05)',
  },
  optionIconContainer: {
    marginRight: spacing.lg,
  },
  optionIcon: {
    width: 48,
    height: 48,
    borderRadius: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionContent: {
    flex: 1,
  },
  optionTitle: {
    fontSize: spacing.lg,
    fontWeight: '600',
    color: colors.gray900,
    marginBottom: spacing.xs,
  },
  optionDescription: {
    fontSize: 14,
    color: colors.gray500,
    lineHeight: spacing.xl,
  },
  radioButton: {
    width: spacing.xl,
    height: spacing.xl,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.gray500,
    backgroundColor: 'transparent',
  },
  radioButtonSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.gray900,
    marginBottom: spacing.lg,
    marginTop: spacing.lg,
  },
  membershipFeeContainer: {
    flexDirection: 'row',
    marginTop: spacing.md,
    gap: spacing.md,
  },
  currencySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    minWidth: 80,
  },
  currencyText: {
    color: colors.gray900,
    fontSize: 14,
    fontWeight: '500',
    marginRight: spacing.sm,
  },
  feeInput: {
    flex: 1,
    backgroundColor: 'white',
    borderRadius: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    color: colors.gray900,
    fontSize: spacing.lg,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: colors.gray800,
    borderRadius: spacing.md,
    padding: spacing.xl,
    width: '80%',
    maxWidth: 300,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: 'white',
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  currencyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: spacing.sm,
    marginBottom: spacing.sm,
  },
  currencyOptionSelected: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
  },
  currencyCode: {
    fontSize: spacing.lg,
    fontWeight: '600',
    color: 'white',
    marginRight: spacing.sm,
  },
  currencyName: {
    fontSize: 14,
    color: colors.gray400,
    flex: 1,
  },
  socialLinksContainer: {
    gap: spacing.lg,
  },
  socialLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
  },
  socialIconContainer: {
    width: 48,
    height: 48,
  },
  socialIcon: {
    width: 48,
    height: 48,
    borderRadius: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialInput: {
    flex: 1,
    backgroundColor: 'white',
    borderRadius: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    color: colors.gray900,
    fontSize: spacing.lg,
  },
  photoUploadContainer: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  photoUploadButton: {
    marginBottom: spacing.sm,
  },
  photoUploadGradient: {
    width: 80,
    height: 80,
    borderRadius: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedImage: {
    width: 76,
    height: 76,
    borderRadius: 18,
  },
  photoUploadText: {
    fontSize: 14,
    color: colors.gray500,
    textAlign: 'center',
  },
  inputError: {
    borderColor: colors.errorDark,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  modalCloseButton: {
    fontSize: spacing.xl,
    color: colors.gray400,
    fontWeight: '600',
  },
  currencySymbol: {
    fontSize: spacing.xl,
    fontWeight: '600',
    color: 'white',
    width: 40,
    textAlign: 'center',
  },
  currencyInfo: {
    flex: 1,
    marginLeft: spacing.md,
  },
  checkMark: {
    fontSize: spacing.lg,
    color: colors.success,
    fontWeight: '600',
  },
  // Success Page Styles
  successCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: spacing.xxxl,
    padding: 40,
    margin: spacing.xl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  successDecorations: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 100,
  },
  successDecorationLeft: {
    position: 'absolute',
    top: spacing.xl,
    left: 30,
  },
  successDecorationRight: {
    position: 'absolute',
    top: spacing.xl,
    right: 30,
  },
  successIconContainer: {
    marginBottom: spacing.xxl,
    marginTop: spacing.xl,
  },
  successCheckContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCheckGradient: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: spacing.sm,
    elevation: spacing.sm,
  },
  successCheckIcon: {
    fontSize: spacing.xxxl,
    color: 'white',
    fontWeight: 'bold',
  },
  successPartyIcon: {
    fontSize: spacing.xxl,
  },
  successStarIcon: {
    fontSize: spacing.xl,
  },
  successContent: {
    alignItems: 'center',
    width: '100%',
  },
  successTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.gray800,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  successSubtitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.gray700,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  successDescription: {
    fontSize: spacing.lg,
    color: colors.gray500,
    textAlign: 'center',
    lineHeight: spacing.xxl,
    marginBottom: spacing.xxxl,
  },
  successFeatures: {
    width: '100%',
    marginBottom: spacing.xxxl,
  },
  successFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: spacing.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  successFeatureIcon: {
    fontSize: spacing.xl,
    marginRight: spacing.md,
  },
  successFeatureText: {
    fontSize: spacing.lg,
    color: colors.gray700,
    fontWeight: '500',
  },
  successActions: {
    width: '100%',
    gap: spacing.lg,
  },
  successPrimaryButton: {
    borderRadius: spacing.xl,
    overflow: 'hidden',
  },
  successButtonGradient: {
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxxl,
    alignItems: 'center',
  },
  successPrimaryButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: 'white',
    textAlign: 'center',
  },
  successSecondaryButton: {
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxxl,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: spacing.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  successSecondaryButtonText: {
    fontSize: spacing.lg,
    color: colors.gray700,
    textAlign: 'center',
    fontWeight: '500',
  },
  successParticles: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  successParticle: {
    position: 'absolute',
    top: Math.random() * 200 + 100,
  },
  successParticleText: {
    fontSize: spacing.lg,
    opacity: 0.7,
  },
  // Modern Success Styles
  modernFloatingElement: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    opacity: 0.3,
  },
  modernElement1: {
    top: '15%',
    left: '10%',
  },
  modernElement2: {
    top: '25%',
    right: '15%',
  },
  modernElement3: {
    bottom: '20%',
    left: '20%',
  },
  modernFloatingGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
  },
  modernSuccessCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 40,
    padding: 40,
    margin: spacing.xl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
    elevation: spacing.xl,
  },
  modernSuccessIcon: {
    marginBottom: spacing.xxxl,
    position: 'relative',
  },
  modernIconGradient: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.successGradientStart,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: spacing.xl,
    elevation: 15,
  },
  modernCheckIcon: {
    fontSize: 40,
    color: 'white',
    fontWeight: '900',
  },
  modernIconGlow: {
    position: 'absolute',
    top: -10,
    left: -10,
    right: -10,
    bottom: -10,
    borderRadius: 60,
    backgroundColor: 'rgba(0, 242, 96, 0.2)',
    opacity: 0.8,
  },
  modernContent: {
    alignItems: 'center',
    width: '100%',
  },
  modernTitle: {
    fontSize: spacing.xxxl,
    fontWeight: '900',
    color: 'white',
    textAlign: 'center',
    marginBottom: spacing.md,
    letterSpacing: 1,
  },
  modernSubtitle: {
    fontSize: spacing.xl,
    fontWeight: '700',
    color: colors.gray200,
    textAlign: 'center',
    marginBottom: spacing.lg,
    lineHeight: 28,
  },
  modernDescription: {
    fontSize: spacing.lg,
    color: colors.gray400,
    textAlign: 'center',
    lineHeight: spacing.xxl,
    marginBottom: 40,
    opacity: 0.9,
  },
  modernStats: {
    width: '100%',
    marginBottom: 40,
    gap: spacing.xl,
  },
  modernStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: spacing.xl,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modernStatIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.lg,
  },
  modernStatEmoji: {
    fontSize: 22,
  },
  modernStatText: {
    fontSize: spacing.lg,
    color: 'white',
    fontWeight: '600',
    flex: 1,
  },
  modernActions: {
    width: '100%',
    gap: spacing.xl,
  },
  modernPrimaryButton: {
    borderRadius: 25,
    overflow: 'hidden',
    shadowColor: colors.modernGradientStart,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
  },
  modernButtonGradient: {
    paddingVertical: spacing.xl,
    paddingHorizontal: spacing.xxxl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modernPrimaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: 'white',
    marginRight: spacing.sm,
  },
  modernButtonIcon: {
    fontSize: 18,
    color: 'white',
    fontWeight: '600',
  },
  modernSecondaryButton: {
    paddingVertical: 18,
    paddingHorizontal: spacing.xxxl,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  modernSecondaryButtonText: {
    fontSize: spacing.lg,
    color: colors.gray200,
    textAlign: 'center',
    fontWeight: '600',
  },
  // Minimalist Success Styles (inspired by the image)
  minimalistBackground: {
    flex: 1,
  },
  confettiParticle: {
    position: 'absolute',
    top: 0,
  },
  confettiShape: {
    fontSize: spacing.lg,
    fontWeight: 'bold',
  },
  spiralContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  spiral: {
    position: 'absolute',
    fontSize: spacing.xxl,
    opacity: 0.6,
  },
  spiral1: {
    top: '20%',
    right: '25%',
    transform: [{ rotate: '45deg' }],
  },
  spiral2: {
    bottom: '30%',
    left: '15%',
    transform: [{ rotate: '-30deg' }],
  },
  spiral3: {
    top: '60%',
    right: '10%',
    transform: [{ rotate: '120deg' }],
  },
  minimalistContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  minimalistContent: {
    alignItems: 'center',
    width: '100%',
  },
  minimalistIconContainer: {
    marginBottom: 40,
    alignItems: 'center',
  },
  minimalistIcon: {
    backgroundColor: colors.minimalistYellow,
    borderRadius: spacing.xxl,
    padding: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: spacing.lg,
    elevation: spacing.sm,
  },
  iconGrid: {
    width: 120,
    height: 120,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  iconCell: {
    width: 40,
    height: 40,
    backgroundColor: colors.minimalistYellowLight,
    borderRadius: spacing.sm,
    margin: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.minimalistYellowDark,
  },
  iconCellCenter: {
    backgroundColor: colors.minimalistOrange,
    borderColor: '#E67E22',
  },
  iconFace: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  iconEyes: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  iconEye: {
    width: 3,
    height: 3,
    backgroundColor: colors.minimalistDark,
    borderRadius: 1.5,
    marginHorizontal: 2,
  },
  iconMouth: {
    width: spacing.sm,
    height: 2,
    backgroundColor: colors.minimalistDark,
    borderRadius: 1,
  },
  minimalistTitle: {
    fontSize: spacing.xxxl,
    fontWeight: '900',
    color: colors.minimalistDark,
    textAlign: 'center',
    marginBottom: spacing.sm,
    letterSpacing: -0.5,
  },
  minimalistSubtitle: {
    fontSize: 18,
    color: colors.minimalistGray,
    textAlign: 'center',
    marginBottom: 60,
    fontWeight: '400',
  },
  minimalistActions: {
    width: '100%',
    gap: spacing.lg,
  },
  minimalistPrimaryButton: {
    backgroundColor: colors.minimalistDark,
    paddingVertical: 18,
    paddingHorizontal: spacing.xxxl,
    borderRadius: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.sm,
    elevation: spacing.xs,
  },
  minimalistPrimaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: 'white',
    textAlign: 'center',
  },
  minimalistSecondaryButton: {
    backgroundColor: 'transparent',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxxl,
    borderRadius: spacing.lg,
    borderWidth: 1,
    borderColor: colors.minimalistBorder,
  },
  minimalistSecondaryButtonText: {
    fontSize: spacing.lg,
    color: colors.minimalistGray,
    textAlign: 'center',
    fontWeight: '600',
  },
  

});

export default styles;




