import { StyleSheet } from 'react-native';
import { borderRadius, colors, fontSize, fontWeight, spacing } from '../../../../lib/design-tokens';

export const styles = StyleSheet.create({
  // ===== STYLES COMMUNS =====
  container: {
    flex: 1,
    backgroundColor: colors.gray50,
  },
  tabsContainer: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  tab: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    marginRight: spacing.sm,
    borderRadius: 20,
    backgroundColor: colors.gray100,
  },
  activeTab: {
    backgroundColor: colors.productsPrimary,
  },
  tabText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    color: colors.gray600,
    textAlign: 'center',
  },
  activeTabText: {
    color: colors.white,
    fontWeight: fontWeight.bold,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  // ===== STYLES SPÉCIFIQUES À LA LISTE =====
  header: {
    backgroundColor: colors.productsPrimary,
    borderRadius: borderRadius.lg,
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
    paddingVertical: spacing.xl,
    paddingHorizontal: spacing.xl,
    position: 'relative',
    overflow: 'hidden',
  },
  backgroundCircle1: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  backgroundCircle2: {
    position: 'absolute',
    bottom: -30,
    left: -30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  titleSection: {
    flex: 0.6,
    marginRight: spacing.lg,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
    flexWrap: 'nowrap',
  },
  title: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    color: colors.white,
    marginLeft: 6,
    flexShrink: 0,
  },
  subtitle: {
    fontSize: fontSize.xs,
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 16,
  },
  statsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 0.4,
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  statItem: {
    alignItems: 'center',
    width: 42,
    marginBottom: spacing.xs,
  },
  statNumber: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.white,
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 8,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    lineHeight: 10,
    flexWrap: 'wrap',
  },
  searchContainer: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  searchIcon: {
    marginRight: spacing.sm,
  },
  searchInput: {
    flex: 1,
    fontSize: fontSize.sm,
    color: colors.gray800,
    padding: 0,
  },
  productsList: {
    paddingHorizontal: spacing.lg,
    paddingBottom: 100,
  },
  row: {
    justifyContent: 'space-between',
  },
  productCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    marginBottom: spacing.lg,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flex: 1,
    marginHorizontal: 4,
  },
  productImageContainer: {
    position: 'relative',
  },
  productImage: {
    width: '100%',
    height: 120,
    backgroundColor: colors.gray100,
  },
  badgeContainer: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  badge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.lg,
  },
  ownedBadge: {
    backgroundColor: colors.success,
  },
  freeBadge: {
    backgroundColor: colors.primary,
  },
  priceBadge: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  badgeText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: fontWeight.semibold,
  },
  productContent: {
    padding: spacing.md,
  },
  productHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  productTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    color: colors.gray800,
    flex: 1,
    marginRight: spacing.sm,
  },
  ratingText: {
    fontSize: 11,
    color: colors.gray500,
    marginLeft: spacing.xs,
  },
  productDescription: {
    fontSize: fontSize.xs,
    color: colors.gray500,
    marginBottom: spacing.md,
    lineHeight: 16,
  },
  productMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  categoryBadge: {
    backgroundColor: colors.gray100,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: borderRadius.md,
  },
  categoryText: {
    fontSize: fontSize.xs,
    color: colors.gray500,
    fontWeight: fontWeight.medium,
  },
  downloadCount: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  downloadCountText: {
    fontSize: fontSize.xs,
    color: colors.gray500,
    marginLeft: spacing.xs,
  },
  creatorInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  creatorAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.gray200,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  creatorInitial: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.gray500,
  },
  creatorName: {
    fontSize: 11,
    color: colors.gray500,
  },
  productActions: {
    marginTop: spacing.xs,
  },
  actionButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  downloadButton: {
    backgroundColor: colors.success,
  },
  purchaseButton: {
    backgroundColor: colors.productsPrimary,
  },
  downloadButtonText: {
    color: colors.white,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    marginLeft: spacing.xs,
  },
  purchaseButtonText: {
    color: colors.white,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  emptyStateTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.gray600,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  emptyStateText: {
    fontSize: fontSize.sm,
    color: colors.gray500,
    textAlign: 'center',
  },

  // ===== STYLES SPÉCIFIQUES AU DÉTAIL =====
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
    paddingBottom: 150,
  },
  content: {
    paddingBottom: 40,
  },
  notFound: {
    fontSize: fontSize.base,
    textAlign: 'center',
    color: '#666',
  },
  imageContainer: {
    height: 250,
    backgroundColor: colors.gray100,
    position: 'relative',
  },
  detailProductImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  productInfo: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray200,
  },
  creatorDetails: {
    flex: 1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  creatorText: {
    fontSize: fontSize.sm,
    color: '#666',
    marginBottom: spacing.xs,
  },
  rating: {
    fontSize: fontSize.xs,
    color: '#666',
    marginLeft: spacing.xs,
  },
  messageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  messageText: {
    color: colors.productsPrimary,
    fontWeight: fontWeight.medium,
    marginLeft: spacing.sm,
  },
  tabContainer: {
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray200,
    paddingVertical: spacing.sm,
  },
  tabScrollView: {
    paddingHorizontal: spacing.lg,
  },
  tabContent: {
    padding: spacing.lg,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  cardTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    color: '#333',
    marginBottom: spacing.sm,
  },
  cardSubtitle: {
    fontSize: fontSize.sm,
    color: '#666',
    marginBottom: spacing.lg,
  },
  cardDescription: {
    fontSize: fontSize.sm,
    color: '#333',
    marginBottom: spacing.md,
  },
  cardText: {
    fontSize: fontSize.sm,
    color: '#666',
    lineHeight: 20,
    marginBottom: spacing.lg,
  },
  featureTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: '#333',
    marginBottom: spacing.sm,
  },
  detailsCard: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    margin: spacing.lg,
    marginBottom: 60,
    borderRadius: borderRadius.lg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  detailsTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: '#333',
    marginBottom: spacing.md,
  },
  detailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  detailsLabel: {
    fontSize: fontSize.sm,
    color: '#666',
  },
  detailsValue: {
    fontSize: fontSize.sm,
    color: '#333',
    fontWeight: fontWeight.medium,
  },
  fileTypes: {
    flexDirection: 'row',
  },
  fileTypeBadge: {
    backgroundColor: colors.gray100,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: borderRadius.sm,
    marginLeft: spacing.xs,
  },
  fileTypeText: {
    fontSize: fontSize.xs,
    color: '#666',
    fontWeight: fontWeight.medium,
  },

  fileCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.gray200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  fileCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fileMainInfo: {
    flex: 1,
    marginRight: spacing.md,
  },
  fileMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    flexWrap: 'wrap',
  },
  fileMetaBadge: {
    backgroundColor: colors.productsPrimary,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.md,
    marginRight: spacing.xs,
    marginBottom: spacing.xs,
  },
  fileMetaText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: fontWeight.semibold,
  },
  fileMetaBadgeMuted: {
    backgroundColor: colors.gray100,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.md,
    marginRight: spacing.xs,
    marginBottom: spacing.xs,
  },
  fileMetaTextMuted: {
    color: colors.gray600,
    fontSize: 10,
    fontWeight: fontWeight.semibold,
  },
  fileRightColumn: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  fileCardBottomRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },

  filePill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  filePillLocked: {
    backgroundColor: colors.gray100,
    borderColor: colors.gray200,
  },
  filePillPaid: {
    backgroundColor: 'rgba(142, 120, 251, 0.12)',
    borderColor: 'rgba(142, 120, 251, 0.25)',
  },
  filePillFree: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    borderColor: 'rgba(34, 197, 94, 0.25)',
  },
  filePillText: {
    marginLeft: spacing.xs,
    fontSize: 11,
    color: colors.gray700,
    fontWeight: fontWeight.semibold,
  },

  fileActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: 10,
    borderRadius: borderRadius.md,
    minWidth: 120,
  },
  fileActionButtonPrimary: {
    backgroundColor: colors.productsPrimary,
  },
  fileActionButtonSuccess: {
    backgroundColor: colors.success,
  },
  fileActionButtonDisabled: {
    backgroundColor: colors.gray100,
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  fileActionButtonText: {
    color: colors.white,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    marginLeft: spacing.xs,
  },
  fileActionButtonTextDisabled: {
    color: colors.gray600,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    marginLeft: spacing.xs,
  },

  fileItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderWidth: 1,
    borderColor: colors.gray200,
    borderRadius: borderRadius.md,
    marginBottom: spacing.md,
    backgroundColor: colors.gray50,
  },
  fileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  fileIcon: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.md,
    backgroundColor: colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  fileName: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: '#333',
    marginBottom: 2,
  },
  fileDetails: {
    fontSize: fontSize.xs,
    color: '#666',
  },
  buyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.success,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: borderRadius.sm,
  },
  buyButtonText: {
    color: colors.white,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    marginLeft: spacing.xs,
  },
  lockedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.gray100,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: borderRadius.sm,
  },
  lockedButtonText: {
    color: '#666',
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    marginLeft: spacing.xs,
  },
  progressContainer: {
    width: 80,
  },
  progressBar: {
    height: 4,
    backgroundColor: colors.gray200,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.productsPrimary,
  },

  reviewComposer: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.gray200,
  },
  reviewComposerTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.gray800,
    marginBottom: spacing.sm,
  },
  reviewStarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  reviewStarButton: {
    paddingRight: 8,
    paddingVertical: 4,
  },
  reviewInput: {
    minHeight: 90,
    borderWidth: 1,
    borderColor: colors.gray200,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    color: colors.gray800,
    backgroundColor: colors.gray50,
    textAlignVertical: 'top',
  },
  reviewSubmitButton: {
    marginTop: spacing.md,
    backgroundColor: colors.productsPrimary,
    borderRadius: borderRadius.md,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewSubmitButtonDisabled: {
    backgroundColor: colors.gray100,
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  reviewSubmitText: {
    color: colors.white,
    fontWeight: fontWeight.semibold,
    fontSize: fontSize.sm,
  },
  reviewSubmitTextDisabled: {
    color: colors.gray600,
  },

  reviewItem: {
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray100,
  },
  reviewHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    overflow: 'hidden',
  },
  reviewAvatarInitial: {
    fontSize: 12,
    fontWeight: fontWeight.bold,
    color: colors.productsPrimary,
  },
  reviewHeaderInfo: {
    flex: 1,
  },
  reviewUserName: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    color: colors.gray800,
  },
  reviewMetaRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reviewRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewRatingText: {
    marginLeft: 6,
    fontSize: fontSize.xs,
    color: colors.gray600,
    fontWeight: fontWeight.semibold,
  },
  reviewDateText: {
    fontSize: fontSize.xs,
    color: colors.gray500,
  },
  reviewMessageText: {
    marginTop: spacing.sm,
    fontSize: fontSize.sm,
    color: colors.gray700,
    lineHeight: 20,
  },
  licenseText: {
    fontSize: fontSize.sm,
    color: '#333',
    lineHeight: 20,
  },
  commentContainer: {
    marginBottom: spacing.lg,
  },
  comment: {
    marginBottom: spacing.md,
  },
  commentHeader: {
    flexDirection: 'row',
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  commentInfo: {
    flex: 1,
  },
  commentText: {
    fontSize: fontSize.sm,
    color: '#333',
    backgroundColor: colors.gray50,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    marginBottom: spacing.sm,
  },
  commentActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  commentMeta: {
    fontSize: fontSize.xs,
    color: '#666',
    marginRight: spacing.lg,
  },
  commentAction: {
    fontSize: fontSize.xs,
    color: colors.productsPrimary,
    fontWeight: fontWeight.medium,
    marginRight: spacing.lg,
  },
  joinButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  joinButtonText: {
    color: colors.productsPrimary,
    fontWeight: fontWeight.medium,
    marginLeft: spacing.sm,
  },
});
